baseURL = "https://nray-scanner.org/"
languageCode = "en-us"
title = "nray"

publishDir = "docs"
pygmentsCodeFences = true

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
[params]
  themeVariant = "blue"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]


